#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T02_Source_Code
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RUP")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChucVu(ChucVu instance);
    partial void UpdateChucVu(ChucVu instance);
    partial void DeleteChucVu(ChucVu instance);
    partial void InsertHoKhau(HoKhau instance);
    partial void UpdateHoKhau(HoKhau instance);
    partial void DeleteHoKhau(HoKhau instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertNhanKhau(NhanKhau instance);
    partial void UpdateNhanKhau(NhanKhau instance);
    partial void DeleteNhanKhau(NhanKhau instance);
    partial void InsertPhuongXa(PhuongXa instance);
    partial void UpdatePhuongXa(PhuongXa instance);
    partial void DeletePhuongXa(PhuongXa instance);
    partial void InsertQuanHuyen(QuanHuyen instance);
    partial void UpdateQuanHuyen(QuanHuyen instance);
    partial void DeleteQuanHuyen(QuanHuyen instance);
    partial void InsertTinhThanh(TinhThanh instance);
    partial void UpdateTinhThanh(TinhThanh instance);
    partial void DeleteTinhThanh(TinhThanh instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::T02_Source_Code.Properties.Settings.Default.RUPConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChucVu> ChucVus
		{
			get
			{
				return this.GetTable<ChucVu>();
			}
		}
		
		public System.Data.Linq.Table<HoKhau> HoKhaus
		{
			get
			{
				return this.GetTable<HoKhau>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<NhanKhau> NhanKhaus
		{
			get
			{
				return this.GetTable<NhanKhau>();
			}
		}
		
		public System.Data.Linq.Table<PhuongXa> PhuongXas
		{
			get
			{
				return this.GetTable<PhuongXa>();
			}
		}
		
		public System.Data.Linq.Table<QuanHuyen> QuanHuyens
		{
			get
			{
				return this.GetTable<QuanHuyen>();
			}
		}
		
		public System.Data.Linq.Table<TinhThanh> TinhThanhs
		{
			get
			{
				return this.GetTable<TinhThanh>();
			}
		}
		
		public System.Data.Linq.Table<TinhQuanHuyen> TinhQuanHuyens
		{
			get
			{
				return this.GetTable<TinhQuanHuyen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChucVu")]
	public partial class ChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaChucVu;
		
		private string _TenChucVu;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChucVuChanging(string value);
    partial void OnMaChucVuChanged();
    partial void OnTenChucVuChanging(string value);
    partial void OnTenChucVuChanged();
    #endregion
		
		public ChucVu()
		{
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChucVu", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaChucVu
		{
			get
			{
				return this._MaChucVu;
			}
			set
			{
				if ((this._MaChucVu != value))
				{
					this.OnMaChucVuChanging(value);
					this.SendPropertyChanging();
					this._MaChucVu = value;
					this.SendPropertyChanged("MaChucVu");
					this.OnMaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChucVu", DbType="NVarChar(50)")]
		public string TenChucVu
		{
			get
			{
				return this._TenChucVu;
			}
			set
			{
				if ((this._TenChucVu != value))
				{
					this.OnTenChucVuChanging(value);
					this.SendPropertyChanging();
					this._TenChucVu = value;
					this.SendPropertyChanged("TenChucVu");
					this.OnTenChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_NguoiDung", Storage="_NguoiDungs", ThisKey="MaChucVu", OtherKey="MaChucVu")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoKhau")]
	public partial class HoKhau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoKhau;
		
		private string _MaPhuongXa;
		
		private string _TenChuHo;
		
		private System.Nullable<int> _SoThanhVien;
		
		private string _NoiThuongTru;
		
		private string _NoiCap;
		
		private System.Nullable<System.DateTime> _NgayCap;
		
		private string _NguoiCap;
		
		private System.Nullable<int> _HoSoHKSo;
		
		private System.Nullable<int> _SoDKThuongTru;
		
		private EntitySet<NhanKhau> _NhanKhaus;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
		private EntityRef<PhuongXa> _PhuongXa;
		
		private EntityRef<PhuongXa> _PhuongXa1;
		
		private EntityRef<PhuongXa> _PhuongXa2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoKhauChanging(string value);
    partial void OnMaHoKhauChanged();
    partial void OnMaPhuongXaChanging(string value);
    partial void OnMaPhuongXaChanged();
    partial void OnTenChuHoChanging(string value);
    partial void OnTenChuHoChanged();
    partial void OnSoThanhVienChanging(System.Nullable<int> value);
    partial void OnSoThanhVienChanged();
    partial void OnNoiThuongTruChanging(string value);
    partial void OnNoiThuongTruChanged();
    partial void OnNoiCapChanging(string value);
    partial void OnNoiCapChanged();
    partial void OnNgayCapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapChanged();
    partial void OnNguoiCapChanging(string value);
    partial void OnNguoiCapChanged();
    partial void OnHoSoHKSoChanging(System.Nullable<int> value);
    partial void OnHoSoHKSoChanged();
    partial void OnSoDKThuongTruChanging(System.Nullable<int> value);
    partial void OnSoDKThuongTruChanged();
    #endregion
		
		public HoKhau()
		{
			this._NhanKhaus = new EntitySet<NhanKhau>(new Action<NhanKhau>(this.attach_NhanKhaus), new Action<NhanKhau>(this.detach_NhanKhaus));
			this._NguoiDung = default(EntityRef<NguoiDung>);
			this._PhuongXa = default(EntityRef<PhuongXa>);
			this._PhuongXa1 = default(EntityRef<PhuongXa>);
			this._PhuongXa2 = default(EntityRef<PhuongXa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoKhau", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoKhau
		{
			get
			{
				return this._MaHoKhau;
			}
			set
			{
				if ((this._MaHoKhau != value))
				{
					this.OnMaHoKhauChanging(value);
					this.SendPropertyChanging();
					this._MaHoKhau = value;
					this.SendPropertyChanged("MaHoKhau");
					this.OnMaHoKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhuongXa", DbType="NChar(10)")]
		public string MaPhuongXa
		{
			get
			{
				return this._MaPhuongXa;
			}
			set
			{
				if ((this._MaPhuongXa != value))
				{
					if (this._PhuongXa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhuongXaChanging(value);
					this.SendPropertyChanging();
					this._MaPhuongXa = value;
					this.SendPropertyChanged("MaPhuongXa");
					this.OnMaPhuongXaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChuHo", DbType="NVarChar(50)")]
		public string TenChuHo
		{
			get
			{
				return this._TenChuHo;
			}
			set
			{
				if ((this._TenChuHo != value))
				{
					this.OnTenChuHoChanging(value);
					this.SendPropertyChanging();
					this._TenChuHo = value;
					this.SendPropertyChanged("TenChuHo");
					this.OnTenChuHoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoThanhVien", DbType="Int")]
		public System.Nullable<int> SoThanhVien
		{
			get
			{
				return this._SoThanhVien;
			}
			set
			{
				if ((this._SoThanhVien != value))
				{
					this.OnSoThanhVienChanging(value);
					this.SendPropertyChanging();
					this._SoThanhVien = value;
					this.SendPropertyChanged("SoThanhVien");
					this.OnSoThanhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiThuongTru", DbType="NChar(10)")]
		public string NoiThuongTru
		{
			get
			{
				return this._NoiThuongTru;
			}
			set
			{
				if ((this._NoiThuongTru != value))
				{
					if (this._PhuongXa1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNoiThuongTruChanging(value);
					this.SendPropertyChanging();
					this._NoiThuongTru = value;
					this.SendPropertyChanged("NoiThuongTru");
					this.OnNoiThuongTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiCap", DbType="NChar(10)")]
		public string NoiCap
		{
			get
			{
				return this._NoiCap;
			}
			set
			{
				if ((this._NoiCap != value))
				{
					if (this._PhuongXa2.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNoiCapChanging(value);
					this.SendPropertyChanging();
					this._NoiCap = value;
					this.SendPropertyChanged("NoiCap");
					this.OnNoiCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayCap
		{
			get
			{
				return this._NgayCap;
			}
			set
			{
				if ((this._NgayCap != value))
				{
					this.OnNgayCapChanging(value);
					this.SendPropertyChanging();
					this._NgayCap = value;
					this.SendPropertyChanged("NgayCap");
					this.OnNgayCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCap", DbType="NChar(10)")]
		public string NguoiCap
		{
			get
			{
				return this._NguoiCap;
			}
			set
			{
				if ((this._NguoiCap != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNguoiCapChanging(value);
					this.SendPropertyChanging();
					this._NguoiCap = value;
					this.SendPropertyChanged("NguoiCap");
					this.OnNguoiCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoSoHKSo", DbType="Int")]
		public System.Nullable<int> HoSoHKSo
		{
			get
			{
				return this._HoSoHKSo;
			}
			set
			{
				if ((this._HoSoHKSo != value))
				{
					this.OnHoSoHKSoChanging(value);
					this.SendPropertyChanging();
					this._HoSoHKSo = value;
					this.SendPropertyChanged("HoSoHKSo");
					this.OnHoSoHKSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDKThuongTru", DbType="Int")]
		public System.Nullable<int> SoDKThuongTru
		{
			get
			{
				return this._SoDKThuongTru;
			}
			set
			{
				if ((this._SoDKThuongTru != value))
				{
					this.OnSoDKThuongTruChanging(value);
					this.SendPropertyChanging();
					this._SoDKThuongTru = value;
					this.SendPropertyChanged("SoDKThuongTru");
					this.OnSoDKThuongTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoKhau_NhanKhau", Storage="_NhanKhaus", ThisKey="MaHoKhau", OtherKey="MaHoKhau")]
		public EntitySet<NhanKhau> NhanKhaus
		{
			get
			{
				return this._NhanKhaus;
			}
			set
			{
				this._NhanKhaus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_HoKhau", Storage="_NguoiDung", ThisKey="NguoiCap", OtherKey="MaNguoiDung", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.HoKhaus.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.HoKhaus.Add(this);
						this._NguoiCap = value.MaNguoiDung;
					}
					else
					{
						this._NguoiCap = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuongXa_HoKhau", Storage="_PhuongXa", ThisKey="MaPhuongXa", OtherKey="MaPhuongXa", IsForeignKey=true)]
		public PhuongXa PhuongXa
		{
			get
			{
				return this._PhuongXa.Entity;
			}
			set
			{
				PhuongXa previousValue = this._PhuongXa.Entity;
				if (((previousValue != value) 
							|| (this._PhuongXa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhuongXa.Entity = null;
						previousValue.HoKhaus.Remove(this);
					}
					this._PhuongXa.Entity = value;
					if ((value != null))
					{
						value.HoKhaus.Add(this);
						this._MaPhuongXa = value.MaPhuongXa;
					}
					else
					{
						this._MaPhuongXa = default(string);
					}
					this.SendPropertyChanged("PhuongXa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuongXa_HoKhau1", Storage="_PhuongXa1", ThisKey="NoiThuongTru", OtherKey="MaPhuongXa", IsForeignKey=true)]
		public PhuongXa PhuongXa1
		{
			get
			{
				return this._PhuongXa1.Entity;
			}
			set
			{
				PhuongXa previousValue = this._PhuongXa1.Entity;
				if (((previousValue != value) 
							|| (this._PhuongXa1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhuongXa1.Entity = null;
						previousValue.HoKhaus1.Remove(this);
					}
					this._PhuongXa1.Entity = value;
					if ((value != null))
					{
						value.HoKhaus1.Add(this);
						this._NoiThuongTru = value.MaPhuongXa;
					}
					else
					{
						this._NoiThuongTru = default(string);
					}
					this.SendPropertyChanged("PhuongXa1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuongXa_HoKhau2", Storage="_PhuongXa2", ThisKey="NoiCap", OtherKey="MaPhuongXa", IsForeignKey=true)]
		public PhuongXa PhuongXa2
		{
			get
			{
				return this._PhuongXa2.Entity;
			}
			set
			{
				PhuongXa previousValue = this._PhuongXa2.Entity;
				if (((previousValue != value) 
							|| (this._PhuongXa2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhuongXa2.Entity = null;
						previousValue.HoKhaus2.Remove(this);
					}
					this._PhuongXa2.Entity = value;
					if ((value != null))
					{
						value.HoKhaus2.Add(this);
						this._NoiCap = value.MaPhuongXa;
					}
					else
					{
						this._NoiCap = default(string);
					}
					this.SendPropertyChanged("PhuongXa2");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanKhaus(NhanKhau entity)
		{
			this.SendPropertyChanging();
			entity.HoKhau = this;
		}
		
		private void detach_NhanKhaus(NhanKhau entity)
		{
			this.SendPropertyChanging();
			entity.HoKhau = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNguoiDung;
		
		private string _MaTinhThanh;
		
		private string _MaQuanHuyen;
		
		private string _MaPhuongXa;
		
		private string _MaChucVu;
		
		private string _TenNguoiDung;
		
		private string _MatKhau;
		
		private EntitySet<HoKhau> _HoKhaus;
		
		private EntityRef<ChucVu> _ChucVu;
		
		private EntityRef<PhuongXa> _PhuongXa;
		
		private EntityRef<QuanHuyen> _QuanHuyen;
		
		private EntityRef<TinhThanh> _TinhThanh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    partial void OnMaTinhThanhChanging(string value);
    partial void OnMaTinhThanhChanged();
    partial void OnMaQuanHuyenChanging(string value);
    partial void OnMaQuanHuyenChanged();
    partial void OnMaPhuongXaChanging(string value);
    partial void OnMaPhuongXaChanged();
    partial void OnMaChucVuChanging(string value);
    partial void OnMaChucVuChanged();
    partial void OnTenNguoiDungChanging(string value);
    partial void OnTenNguoiDungChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public NguoiDung()
		{
			this._HoKhaus = new EntitySet<HoKhau>(new Action<HoKhau>(this.attach_HoKhaus), new Action<HoKhau>(this.detach_HoKhaus));
			this._ChucVu = default(EntityRef<ChucVu>);
			this._PhuongXa = default(EntityRef<PhuongXa>);
			this._QuanHuyen = default(EntityRef<QuanHuyen>);
			this._TinhThanh = default(EntityRef<TinhThanh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhThanh", DbType="NChar(10)")]
		public string MaTinhThanh
		{
			get
			{
				return this._MaTinhThanh;
			}
			set
			{
				if ((this._MaTinhThanh != value))
				{
					if (this._TinhThanh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTinhThanhChanging(value);
					this.SendPropertyChanging();
					this._MaTinhThanh = value;
					this.SendPropertyChanged("MaTinhThanh");
					this.OnMaTinhThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuanHuyen", DbType="NChar(10)")]
		public string MaQuanHuyen
		{
			get
			{
				return this._MaQuanHuyen;
			}
			set
			{
				if ((this._MaQuanHuyen != value))
				{
					if (this._QuanHuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQuanHuyenChanging(value);
					this.SendPropertyChanging();
					this._MaQuanHuyen = value;
					this.SendPropertyChanged("MaQuanHuyen");
					this.OnMaQuanHuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhuongXa", DbType="NChar(10)")]
		public string MaPhuongXa
		{
			get
			{
				return this._MaPhuongXa;
			}
			set
			{
				if ((this._MaPhuongXa != value))
				{
					if (this._PhuongXa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhuongXaChanging(value);
					this.SendPropertyChanging();
					this._MaPhuongXa = value;
					this.SendPropertyChanged("MaPhuongXa");
					this.OnMaPhuongXaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChucVu", DbType="NChar(10)")]
		public string MaChucVu
		{
			get
			{
				return this._MaChucVu;
			}
			set
			{
				if ((this._MaChucVu != value))
				{
					if (this._ChucVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChucVuChanging(value);
					this.SendPropertyChanging();
					this._MaChucVu = value;
					this.SendPropertyChanged("MaChucVu");
					this.OnMaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiDung", DbType="NVarChar(50)")]
		public string TenNguoiDung
		{
			get
			{
				return this._TenNguoiDung;
			}
			set
			{
				if ((this._TenNguoiDung != value))
				{
					this.OnTenNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiDung = value;
					this.SendPropertyChanged("TenNguoiDung");
					this.OnTenNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_HoKhau", Storage="_HoKhaus", ThisKey="MaNguoiDung", OtherKey="NguoiCap")]
		public EntitySet<HoKhau> HoKhaus
		{
			get
			{
				return this._HoKhaus;
			}
			set
			{
				this._HoKhaus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_NguoiDung", Storage="_ChucVu", ThisKey="MaChucVu", OtherKey="MaChucVu", IsForeignKey=true)]
		public ChucVu ChucVu
		{
			get
			{
				return this._ChucVu.Entity;
			}
			set
			{
				ChucVu previousValue = this._ChucVu.Entity;
				if (((previousValue != value) 
							|| (this._ChucVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChucVu.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._ChucVu.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._MaChucVu = value.MaChucVu;
					}
					else
					{
						this._MaChucVu = default(string);
					}
					this.SendPropertyChanged("ChucVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuongXa_NguoiDung", Storage="_PhuongXa", ThisKey="MaPhuongXa", OtherKey="MaPhuongXa", IsForeignKey=true)]
		public PhuongXa PhuongXa
		{
			get
			{
				return this._PhuongXa.Entity;
			}
			set
			{
				PhuongXa previousValue = this._PhuongXa.Entity;
				if (((previousValue != value) 
							|| (this._PhuongXa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhuongXa.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._PhuongXa.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._MaPhuongXa = value.MaPhuongXa;
					}
					else
					{
						this._MaPhuongXa = default(string);
					}
					this.SendPropertyChanged("PhuongXa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanHuyen_NguoiDung", Storage="_QuanHuyen", ThisKey="MaQuanHuyen", OtherKey="MaQuanHuyen", IsForeignKey=true)]
		public QuanHuyen QuanHuyen
		{
			get
			{
				return this._QuanHuyen.Entity;
			}
			set
			{
				QuanHuyen previousValue = this._QuanHuyen.Entity;
				if (((previousValue != value) 
							|| (this._QuanHuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QuanHuyen.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._QuanHuyen.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._MaQuanHuyen = value.MaQuanHuyen;
					}
					else
					{
						this._MaQuanHuyen = default(string);
					}
					this.SendPropertyChanged("QuanHuyen");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TinhThanh_NguoiDung", Storage="_TinhThanh", ThisKey="MaTinhThanh", OtherKey="MaTinhThanh", IsForeignKey=true)]
		public TinhThanh TinhThanh
		{
			get
			{
				return this._TinhThanh.Entity;
			}
			set
			{
				TinhThanh previousValue = this._TinhThanh.Entity;
				if (((previousValue != value) 
							|| (this._TinhThanh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TinhThanh.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._TinhThanh.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._MaTinhThanh = value.MaTinhThanh;
					}
					else
					{
						this._MaTinhThanh = default(string);
					}
					this.SendPropertyChanged("TinhThanh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoKhaus(HoKhau entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_HoKhaus(HoKhau entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanKhau")]
	public partial class NhanKhau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanKhau;
		
		private string _MaHoKhau;
		
		private string _TenNhanKhau;
		
		private string _TenThuongGoi;
		
		private System.Nullable<bool> _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DanToc;
		
		private string _TonGiao;
		
		private string _QueQuan;
		
		private string _CMND;
		
		private string _NgheNghiep;
		
		private string _NoiLamViec;
		
		private System.Nullable<System.DateTime> _NgayChuyenDen;
		
		private string _NoiThuongTruTruocKhiChuyenDen;
		
		private EntityRef<HoKhau> _HoKhau;
		
		private EntityRef<PhuongXa> _PhuongXa;
		
		private EntityRef<PhuongXa> _PhuongXa1;
		
		private EntityRef<PhuongXa> _PhuongXa2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanKhauChanging(string value);
    partial void OnMaNhanKhauChanged();
    partial void OnMaHoKhauChanging(string value);
    partial void OnMaHoKhauChanged();
    partial void OnTenNhanKhauChanging(string value);
    partial void OnTenNhanKhauChanged();
    partial void OnTenThuongGoiChanging(string value);
    partial void OnTenThuongGoiChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDanTocChanging(string value);
    partial void OnDanTocChanged();
    partial void OnTonGiaoChanging(string value);
    partial void OnTonGiaoChanged();
    partial void OnQueQuanChanging(string value);
    partial void OnQueQuanChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnNgheNghiepChanging(string value);
    partial void OnNgheNghiepChanged();
    partial void OnNoiLamViecChanging(string value);
    partial void OnNoiLamViecChanged();
    partial void OnNgayChuyenDenChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChuyenDenChanged();
    partial void OnNoiThuongTruTruocKhiChuyenDenChanging(string value);
    partial void OnNoiThuongTruTruocKhiChuyenDenChanged();
    #endregion
		
		public NhanKhau()
		{
			this._HoKhau = default(EntityRef<HoKhau>);
			this._PhuongXa = default(EntityRef<PhuongXa>);
			this._PhuongXa1 = default(EntityRef<PhuongXa>);
			this._PhuongXa2 = default(EntityRef<PhuongXa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanKhau", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanKhau
		{
			get
			{
				return this._MaNhanKhau;
			}
			set
			{
				if ((this._MaNhanKhau != value))
				{
					this.OnMaNhanKhauChanging(value);
					this.SendPropertyChanging();
					this._MaNhanKhau = value;
					this.SendPropertyChanged("MaNhanKhau");
					this.OnMaNhanKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoKhau", DbType="NChar(10)")]
		public string MaHoKhau
		{
			get
			{
				return this._MaHoKhau;
			}
			set
			{
				if ((this._MaHoKhau != value))
				{
					if (this._HoKhau.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoKhauChanging(value);
					this.SendPropertyChanging();
					this._MaHoKhau = value;
					this.SendPropertyChanged("MaHoKhau");
					this.OnMaHoKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhanKhau", DbType="NVarChar(50)")]
		public string TenNhanKhau
		{
			get
			{
				return this._TenNhanKhau;
			}
			set
			{
				if ((this._TenNhanKhau != value))
				{
					this.OnTenNhanKhauChanging(value);
					this.SendPropertyChanging();
					this._TenNhanKhau = value;
					this.SendPropertyChanged("TenNhanKhau");
					this.OnTenNhanKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThuongGoi", DbType="NVarChar(50)")]
		public string TenThuongGoi
		{
			get
			{
				return this._TenThuongGoi;
			}
			set
			{
				if ((this._TenThuongGoi != value))
				{
					this.OnTenThuongGoiChanging(value);
					this.SendPropertyChanging();
					this._TenThuongGoi = value;
					this.SendPropertyChanged("TenThuongGoi");
					this.OnTenThuongGoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(50)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this.OnDanTocChanging(value);
					this.SendPropertyChanging();
					this._DanToc = value;
					this.SendPropertyChanged("DanToc");
					this.OnDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TonGiao", DbType="NVarChar(50)")]
		public string TonGiao
		{
			get
			{
				return this._TonGiao;
			}
			set
			{
				if ((this._TonGiao != value))
				{
					this.OnTonGiaoChanging(value);
					this.SendPropertyChanging();
					this._TonGiao = value;
					this.SendPropertyChanged("TonGiao");
					this.OnTonGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueQuan", DbType="NChar(10)")]
		public string QueQuan
		{
			get
			{
				return this._QueQuan;
			}
			set
			{
				if ((this._QueQuan != value))
				{
					if (this._PhuongXa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnQueQuanChanging(value);
					this.SendPropertyChanging();
					this._QueQuan = value;
					this.SendPropertyChanged("QueQuan");
					this.OnQueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(10)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgheNghiep", DbType="NVarChar(50)")]
		public string NgheNghiep
		{
			get
			{
				return this._NgheNghiep;
			}
			set
			{
				if ((this._NgheNghiep != value))
				{
					this.OnNgheNghiepChanging(value);
					this.SendPropertyChanging();
					this._NgheNghiep = value;
					this.SendPropertyChanged("NgheNghiep");
					this.OnNgheNghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiLamViec", DbType="NChar(10)")]
		public string NoiLamViec
		{
			get
			{
				return this._NoiLamViec;
			}
			set
			{
				if ((this._NoiLamViec != value))
				{
					if (this._PhuongXa1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNoiLamViecChanging(value);
					this.SendPropertyChanging();
					this._NoiLamViec = value;
					this.SendPropertyChanged("NoiLamViec");
					this.OnNoiLamViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChuyenDen", DbType="Date")]
		public System.Nullable<System.DateTime> NgayChuyenDen
		{
			get
			{
				return this._NgayChuyenDen;
			}
			set
			{
				if ((this._NgayChuyenDen != value))
				{
					this.OnNgayChuyenDenChanging(value);
					this.SendPropertyChanging();
					this._NgayChuyenDen = value;
					this.SendPropertyChanged("NgayChuyenDen");
					this.OnNgayChuyenDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiThuongTruTruocKhiChuyenDen", DbType="NChar(10)")]
		public string NoiThuongTruTruocKhiChuyenDen
		{
			get
			{
				return this._NoiThuongTruTruocKhiChuyenDen;
			}
			set
			{
				if ((this._NoiThuongTruTruocKhiChuyenDen != value))
				{
					if (this._PhuongXa2.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNoiThuongTruTruocKhiChuyenDenChanging(value);
					this.SendPropertyChanging();
					this._NoiThuongTruTruocKhiChuyenDen = value;
					this.SendPropertyChanged("NoiThuongTruTruocKhiChuyenDen");
					this.OnNoiThuongTruTruocKhiChuyenDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoKhau_NhanKhau", Storage="_HoKhau", ThisKey="MaHoKhau", OtherKey="MaHoKhau", IsForeignKey=true)]
		public HoKhau HoKhau
		{
			get
			{
				return this._HoKhau.Entity;
			}
			set
			{
				HoKhau previousValue = this._HoKhau.Entity;
				if (((previousValue != value) 
							|| (this._HoKhau.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoKhau.Entity = null;
						previousValue.NhanKhaus.Remove(this);
					}
					this._HoKhau.Entity = value;
					if ((value != null))
					{
						value.NhanKhaus.Add(this);
						this._MaHoKhau = value.MaHoKhau;
					}
					else
					{
						this._MaHoKhau = default(string);
					}
					this.SendPropertyChanged("HoKhau");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuongXa_NhanKhau", Storage="_PhuongXa", ThisKey="QueQuan", OtherKey="MaPhuongXa", IsForeignKey=true)]
		public PhuongXa PhuongXa
		{
			get
			{
				return this._PhuongXa.Entity;
			}
			set
			{
				PhuongXa previousValue = this._PhuongXa.Entity;
				if (((previousValue != value) 
							|| (this._PhuongXa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhuongXa.Entity = null;
						previousValue.NhanKhaus.Remove(this);
					}
					this._PhuongXa.Entity = value;
					if ((value != null))
					{
						value.NhanKhaus.Add(this);
						this._QueQuan = value.MaPhuongXa;
					}
					else
					{
						this._QueQuan = default(string);
					}
					this.SendPropertyChanged("PhuongXa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuongXa_NhanKhau1", Storage="_PhuongXa1", ThisKey="NoiLamViec", OtherKey="MaPhuongXa", IsForeignKey=true)]
		public PhuongXa PhuongXa1
		{
			get
			{
				return this._PhuongXa1.Entity;
			}
			set
			{
				PhuongXa previousValue = this._PhuongXa1.Entity;
				if (((previousValue != value) 
							|| (this._PhuongXa1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhuongXa1.Entity = null;
						previousValue.NhanKhaus1.Remove(this);
					}
					this._PhuongXa1.Entity = value;
					if ((value != null))
					{
						value.NhanKhaus1.Add(this);
						this._NoiLamViec = value.MaPhuongXa;
					}
					else
					{
						this._NoiLamViec = default(string);
					}
					this.SendPropertyChanged("PhuongXa1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuongXa_NhanKhau2", Storage="_PhuongXa2", ThisKey="NoiThuongTruTruocKhiChuyenDen", OtherKey="MaPhuongXa", IsForeignKey=true)]
		public PhuongXa PhuongXa2
		{
			get
			{
				return this._PhuongXa2.Entity;
			}
			set
			{
				PhuongXa previousValue = this._PhuongXa2.Entity;
				if (((previousValue != value) 
							|| (this._PhuongXa2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhuongXa2.Entity = null;
						previousValue.NhanKhaus2.Remove(this);
					}
					this._PhuongXa2.Entity = value;
					if ((value != null))
					{
						value.NhanKhaus2.Add(this);
						this._NoiThuongTruTruocKhiChuyenDen = value.MaPhuongXa;
					}
					else
					{
						this._NoiThuongTruTruocKhiChuyenDen = default(string);
					}
					this.SendPropertyChanged("PhuongXa2");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhuongXa")]
	public partial class PhuongXa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhuongXa;
		
		private string _TenPhuongXa;
		
		private string _MaQuanHuyen;
		
		private EntitySet<HoKhau> _HoKhaus;
		
		private EntitySet<HoKhau> _HoKhaus1;
		
		private EntitySet<HoKhau> _HoKhaus2;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
		private EntitySet<NhanKhau> _NhanKhaus;
		
		private EntitySet<NhanKhau> _NhanKhaus1;
		
		private EntitySet<NhanKhau> _NhanKhaus2;
		
		private EntityRef<QuanHuyen> _QuanHuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhuongXaChanging(string value);
    partial void OnMaPhuongXaChanged();
    partial void OnTenPhuongXaChanging(string value);
    partial void OnTenPhuongXaChanged();
    partial void OnMaQuanHuyenChanging(string value);
    partial void OnMaQuanHuyenChanged();
    #endregion
		
		public PhuongXa()
		{
			this._HoKhaus = new EntitySet<HoKhau>(new Action<HoKhau>(this.attach_HoKhaus), new Action<HoKhau>(this.detach_HoKhaus));
			this._HoKhaus1 = new EntitySet<HoKhau>(new Action<HoKhau>(this.attach_HoKhaus1), new Action<HoKhau>(this.detach_HoKhaus1));
			this._HoKhaus2 = new EntitySet<HoKhau>(new Action<HoKhau>(this.attach_HoKhaus2), new Action<HoKhau>(this.detach_HoKhaus2));
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			this._NhanKhaus = new EntitySet<NhanKhau>(new Action<NhanKhau>(this.attach_NhanKhaus), new Action<NhanKhau>(this.detach_NhanKhaus));
			this._NhanKhaus1 = new EntitySet<NhanKhau>(new Action<NhanKhau>(this.attach_NhanKhaus1), new Action<NhanKhau>(this.detach_NhanKhaus1));
			this._NhanKhaus2 = new EntitySet<NhanKhau>(new Action<NhanKhau>(this.attach_NhanKhaus2), new Action<NhanKhau>(this.detach_NhanKhaus2));
			this._QuanHuyen = default(EntityRef<QuanHuyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhuongXa", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhuongXa
		{
			get
			{
				return this._MaPhuongXa;
			}
			set
			{
				if ((this._MaPhuongXa != value))
				{
					this.OnMaPhuongXaChanging(value);
					this.SendPropertyChanging();
					this._MaPhuongXa = value;
					this.SendPropertyChanged("MaPhuongXa");
					this.OnMaPhuongXaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhuongXa", DbType="NVarChar(50)")]
		public string TenPhuongXa
		{
			get
			{
				return this._TenPhuongXa;
			}
			set
			{
				if ((this._TenPhuongXa != value))
				{
					this.OnTenPhuongXaChanging(value);
					this.SendPropertyChanging();
					this._TenPhuongXa = value;
					this.SendPropertyChanged("TenPhuongXa");
					this.OnTenPhuongXaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuanHuyen", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaQuanHuyen
		{
			get
			{
				return this._MaQuanHuyen;
			}
			set
			{
				if ((this._MaQuanHuyen != value))
				{
					if (this._QuanHuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQuanHuyenChanging(value);
					this.SendPropertyChanging();
					this._MaQuanHuyen = value;
					this.SendPropertyChanged("MaQuanHuyen");
					this.OnMaQuanHuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuongXa_HoKhau", Storage="_HoKhaus", ThisKey="MaPhuongXa", OtherKey="MaPhuongXa")]
		public EntitySet<HoKhau> HoKhaus
		{
			get
			{
				return this._HoKhaus;
			}
			set
			{
				this._HoKhaus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuongXa_HoKhau1", Storage="_HoKhaus1", ThisKey="MaPhuongXa", OtherKey="NoiThuongTru")]
		public EntitySet<HoKhau> HoKhaus1
		{
			get
			{
				return this._HoKhaus1;
			}
			set
			{
				this._HoKhaus1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuongXa_HoKhau2", Storage="_HoKhaus2", ThisKey="MaPhuongXa", OtherKey="NoiCap")]
		public EntitySet<HoKhau> HoKhaus2
		{
			get
			{
				return this._HoKhaus2;
			}
			set
			{
				this._HoKhaus2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuongXa_NguoiDung", Storage="_NguoiDungs", ThisKey="MaPhuongXa", OtherKey="MaPhuongXa")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuongXa_NhanKhau", Storage="_NhanKhaus", ThisKey="MaPhuongXa", OtherKey="QueQuan")]
		public EntitySet<NhanKhau> NhanKhaus
		{
			get
			{
				return this._NhanKhaus;
			}
			set
			{
				this._NhanKhaus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuongXa_NhanKhau1", Storage="_NhanKhaus1", ThisKey="MaPhuongXa", OtherKey="NoiLamViec")]
		public EntitySet<NhanKhau> NhanKhaus1
		{
			get
			{
				return this._NhanKhaus1;
			}
			set
			{
				this._NhanKhaus1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhuongXa_NhanKhau2", Storage="_NhanKhaus2", ThisKey="MaPhuongXa", OtherKey="NoiThuongTruTruocKhiChuyenDen")]
		public EntitySet<NhanKhau> NhanKhaus2
		{
			get
			{
				return this._NhanKhaus2;
			}
			set
			{
				this._NhanKhaus2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanHuyen_PhuongXa", Storage="_QuanHuyen", ThisKey="MaQuanHuyen", OtherKey="MaQuanHuyen", IsForeignKey=true)]
		public QuanHuyen QuanHuyen
		{
			get
			{
				return this._QuanHuyen.Entity;
			}
			set
			{
				QuanHuyen previousValue = this._QuanHuyen.Entity;
				if (((previousValue != value) 
							|| (this._QuanHuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QuanHuyen.Entity = null;
						previousValue.PhuongXas.Remove(this);
					}
					this._QuanHuyen.Entity = value;
					if ((value != null))
					{
						value.PhuongXas.Add(this);
						this._MaQuanHuyen = value.MaQuanHuyen;
					}
					else
					{
						this._MaQuanHuyen = default(string);
					}
					this.SendPropertyChanged("QuanHuyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoKhaus(HoKhau entity)
		{
			this.SendPropertyChanging();
			entity.PhuongXa = this;
		}
		
		private void detach_HoKhaus(HoKhau entity)
		{
			this.SendPropertyChanging();
			entity.PhuongXa = null;
		}
		
		private void attach_HoKhaus1(HoKhau entity)
		{
			this.SendPropertyChanging();
			entity.PhuongXa1 = this;
		}
		
		private void detach_HoKhaus1(HoKhau entity)
		{
			this.SendPropertyChanging();
			entity.PhuongXa1 = null;
		}
		
		private void attach_HoKhaus2(HoKhau entity)
		{
			this.SendPropertyChanging();
			entity.PhuongXa2 = this;
		}
		
		private void detach_HoKhaus2(HoKhau entity)
		{
			this.SendPropertyChanging();
			entity.PhuongXa2 = null;
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.PhuongXa = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.PhuongXa = null;
		}
		
		private void attach_NhanKhaus(NhanKhau entity)
		{
			this.SendPropertyChanging();
			entity.PhuongXa = this;
		}
		
		private void detach_NhanKhaus(NhanKhau entity)
		{
			this.SendPropertyChanging();
			entity.PhuongXa = null;
		}
		
		private void attach_NhanKhaus1(NhanKhau entity)
		{
			this.SendPropertyChanging();
			entity.PhuongXa1 = this;
		}
		
		private void detach_NhanKhaus1(NhanKhau entity)
		{
			this.SendPropertyChanging();
			entity.PhuongXa1 = null;
		}
		
		private void attach_NhanKhaus2(NhanKhau entity)
		{
			this.SendPropertyChanging();
			entity.PhuongXa2 = this;
		}
		
		private void detach_NhanKhaus2(NhanKhau entity)
		{
			this.SendPropertyChanging();
			entity.PhuongXa2 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuanHuyen")]
	public partial class QuanHuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaQuanHuyen;
		
		private string _TenQuanHuyen;
		
		private string _MaTinhThanh;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
		private EntitySet<PhuongXa> _PhuongXas;
		
		private EntityRef<TinhThanh> _TinhThanh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQuanHuyenChanging(string value);
    partial void OnMaQuanHuyenChanged();
    partial void OnTenQuanHuyenChanging(string value);
    partial void OnTenQuanHuyenChanged();
    partial void OnMaTinhThanhChanging(string value);
    partial void OnMaTinhThanhChanged();
    #endregion
		
		public QuanHuyen()
		{
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			this._PhuongXas = new EntitySet<PhuongXa>(new Action<PhuongXa>(this.attach_PhuongXas), new Action<PhuongXa>(this.detach_PhuongXas));
			this._TinhThanh = default(EntityRef<TinhThanh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuanHuyen", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaQuanHuyen
		{
			get
			{
				return this._MaQuanHuyen;
			}
			set
			{
				if ((this._MaQuanHuyen != value))
				{
					this.OnMaQuanHuyenChanging(value);
					this.SendPropertyChanging();
					this._MaQuanHuyen = value;
					this.SendPropertyChanged("MaQuanHuyen");
					this.OnMaQuanHuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuanHuyen", DbType="NVarChar(50)")]
		public string TenQuanHuyen
		{
			get
			{
				return this._TenQuanHuyen;
			}
			set
			{
				if ((this._TenQuanHuyen != value))
				{
					this.OnTenQuanHuyenChanging(value);
					this.SendPropertyChanging();
					this._TenQuanHuyen = value;
					this.SendPropertyChanged("TenQuanHuyen");
					this.OnTenQuanHuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhThanh", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaTinhThanh
		{
			get
			{
				return this._MaTinhThanh;
			}
			set
			{
				if ((this._MaTinhThanh != value))
				{
					if (this._TinhThanh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTinhThanhChanging(value);
					this.SendPropertyChanging();
					this._MaTinhThanh = value;
					this.SendPropertyChanged("MaTinhThanh");
					this.OnMaTinhThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanHuyen_NguoiDung", Storage="_NguoiDungs", ThisKey="MaQuanHuyen", OtherKey="MaQuanHuyen")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanHuyen_PhuongXa", Storage="_PhuongXas", ThisKey="MaQuanHuyen", OtherKey="MaQuanHuyen")]
		public EntitySet<PhuongXa> PhuongXas
		{
			get
			{
				return this._PhuongXas;
			}
			set
			{
				this._PhuongXas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TinhThanh_QuanHuyen", Storage="_TinhThanh", ThisKey="MaTinhThanh", OtherKey="MaTinhThanh", IsForeignKey=true)]
		public TinhThanh TinhThanh
		{
			get
			{
				return this._TinhThanh.Entity;
			}
			set
			{
				TinhThanh previousValue = this._TinhThanh.Entity;
				if (((previousValue != value) 
							|| (this._TinhThanh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TinhThanh.Entity = null;
						previousValue.QuanHuyens.Remove(this);
					}
					this._TinhThanh.Entity = value;
					if ((value != null))
					{
						value.QuanHuyens.Add(this);
						this._MaTinhThanh = value.MaTinhThanh;
					}
					else
					{
						this._MaTinhThanh = default(string);
					}
					this.SendPropertyChanged("TinhThanh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.QuanHuyen = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.QuanHuyen = null;
		}
		
		private void attach_PhuongXas(PhuongXa entity)
		{
			this.SendPropertyChanging();
			entity.QuanHuyen = this;
		}
		
		private void detach_PhuongXas(PhuongXa entity)
		{
			this.SendPropertyChanging();
			entity.QuanHuyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinhThanh")]
	public partial class TinhThanh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTinhThanh;
		
		private string _TenTinhThanh;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
		private EntitySet<QuanHuyen> _QuanHuyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTinhThanhChanging(string value);
    partial void OnMaTinhThanhChanged();
    partial void OnTenTinhThanhChanging(string value);
    partial void OnTenTinhThanhChanged();
    #endregion
		
		public TinhThanh()
		{
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			this._QuanHuyens = new EntitySet<QuanHuyen>(new Action<QuanHuyen>(this.attach_QuanHuyens), new Action<QuanHuyen>(this.detach_QuanHuyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhThanh", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTinhThanh
		{
			get
			{
				return this._MaTinhThanh;
			}
			set
			{
				if ((this._MaTinhThanh != value))
				{
					this.OnMaTinhThanhChanging(value);
					this.SendPropertyChanging();
					this._MaTinhThanh = value;
					this.SendPropertyChanged("MaTinhThanh");
					this.OnMaTinhThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTinhThanh", DbType="NVarChar(50)")]
		public string TenTinhThanh
		{
			get
			{
				return this._TenTinhThanh;
			}
			set
			{
				if ((this._TenTinhThanh != value))
				{
					this.OnTenTinhThanhChanging(value);
					this.SendPropertyChanging();
					this._TenTinhThanh = value;
					this.SendPropertyChanged("TenTinhThanh");
					this.OnTenTinhThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TinhThanh_NguoiDung", Storage="_NguoiDungs", ThisKey="MaTinhThanh", OtherKey="MaTinhThanh")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TinhThanh_QuanHuyen", Storage="_QuanHuyens", ThisKey="MaTinhThanh", OtherKey="MaTinhThanh")]
		public EntitySet<QuanHuyen> QuanHuyens
		{
			get
			{
				return this._QuanHuyens;
			}
			set
			{
				this._QuanHuyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.TinhThanh = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.TinhThanh = null;
		}
		
		private void attach_QuanHuyens(QuanHuyen entity)
		{
			this.SendPropertyChanging();
			entity.TinhThanh = this;
		}
		
		private void detach_QuanHuyens(QuanHuyen entity)
		{
			this.SendPropertyChanging();
			entity.TinhThanh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinhQuanHuyen")]
	public partial class TinhQuanHuyen
	{
		
		private string _MaPhuongXa;
		
		private string _TenPhuongXa;
		
		private string _MaQuanHuyen;
		
		private string _TenQuanHuyen;
		
		private string _MaTinhThanh;
		
		private string _TenTinhThanh;
		
		public TinhQuanHuyen()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhuongXa", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaPhuongXa
		{
			get
			{
				return this._MaPhuongXa;
			}
			set
			{
				if ((this._MaPhuongXa != value))
				{
					this._MaPhuongXa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhuongXa", DbType="NVarChar(50)")]
		public string TenPhuongXa
		{
			get
			{
				return this._TenPhuongXa;
			}
			set
			{
				if ((this._TenPhuongXa != value))
				{
					this._TenPhuongXa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuanHuyen", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaQuanHuyen
		{
			get
			{
				return this._MaQuanHuyen;
			}
			set
			{
				if ((this._MaQuanHuyen != value))
				{
					this._MaQuanHuyen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuanHuyen", DbType="NVarChar(50)")]
		public string TenQuanHuyen
		{
			get
			{
				return this._TenQuanHuyen;
			}
			set
			{
				if ((this._TenQuanHuyen != value))
				{
					this._TenQuanHuyen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhThanh", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaTinhThanh
		{
			get
			{
				return this._MaTinhThanh;
			}
			set
			{
				if ((this._MaTinhThanh != value))
				{
					this._MaTinhThanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTinhThanh", DbType="NVarChar(50)")]
		public string TenTinhThanh
		{
			get
			{
				return this._TenTinhThanh;
			}
			set
			{
				if ((this._TenTinhThanh != value))
				{
					this._TenTinhThanh = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
